// AUTO-GENERATED by tools/gen_emblemdata.py — do not edit by hand.
export const EMBLEMDATA = {
 "0": {
  "n": 0,
  "roman": "",
  "mottoEn": "",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "woman_running",
   "man_pursuing",
   "apple_golden",
   "meadow",
   "sky"
  ],
  "imageDesc": "The title-page engraving depicts the race of Atalanta and Hippomenes at the bottom, with Hippomenes in mid-stride casting a golden apple while Atalanta stoops to retrieve one from the ground. At the left margin, Venus extends the golden apples to Hippomenes; at the right, the couple embraces in a te",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-00.jpg"
 },
 "1": {
  "n": 1,
  "roman": "I",
  "mottoEn": "The wind carried it in its belly.",
  "mottoLa": "Nutrix ejus terra est",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "infant",
   "earth_figure",
   "wind_bellowing",
   "nurse_figure",
   "landscape"
  ],
  "imageDesc": "A muscular male figure, identified as Boreas the North Wind, strides across a rocky landscape carrying a swaddled infant against his torso. The wind god's hair and drapery stream behind him, and billowing clouds fill the sky above. Below, a female earth figure — massive, globular, with exposed breas",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-01.jpg"
 },
 "2": {
  "n": 2,
  "roman": "II",
  "mottoEn": "Its nurse is the Earth.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "earth_figure",
   "infant_nursing",
   "landscape",
   "classical_columns"
  ],
  "imageDesc": "The same globular earth-mother figure from Emblem I reappears at center, her body forming a living landscape with a small child nursing at her breast. She sits or reclines against a hillside with a town visible in the distance. Animals — a cow and smaller creatures — graze at her feet, reinforcing h",
  "process": "fermentation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-02.jpg"
 },
 "3": {
  "n": 3,
  "roman": "III",
  "mottoEn": "Go to the woman who washes the sheets and do as she does.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "woman_washing",
   "sheet_cloth",
   "stream_water",
   "sun",
   "wind"
  ],
  "imageDesc": "A woman kneels beside a wooden washing trough in an outdoor setting, scrubbing sheets or linens in soapy water. Her sleeves are rolled up and her posture suggests vigorous labor. A second figure, likely the alchemist-observer, watches from nearby. In the background, linens hang on a line to dry agai",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-03.jpg"
 },
 "4": {
  "n": 4,
  "roman": "IV",
  "mottoEn": "Join brother and sister and give them the cup of love.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "brother_figure",
   "sister_figure",
   "cup_wine",
   "wedding_table",
   "oedipus_sphinx"
  ],
  "imageDesc": "A young man and woman face each other in a formal garden or courtyard setting, joining hands or exchanging a cup between them. Their postures suggest both greeting and ceremonial union. Behind them, architectural elements frame the scene — an archway or portico. The composition centers on the gestur",
  "process": "putrefaction",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-04.jpg"
 },
 "5": {
  "n": 5,
  "roman": "V",
  "mottoEn": "Put a toad to the breasts of a woman, that she may suckle it, and the woman may die and the toad grow big from the milk.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "woman_reclining",
   "toad_large",
   "breasts",
   "milk_stream",
   "death_shadow"
  ],
  "imageDesc": "A woman sits outdoors on a stone bench, her bodice loosened, nursing a large toad at her breast. The toad clings to her chest with its forelimbs, drawing milk while the woman's expression registers calm resignation rather than horror. Behind her, a walled town rises against a hilly landscape with sc",
  "process": "fermentation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-05.jpg"
 },
 "6": {
  "n": 6,
  "roman": "VI",
  "mottoEn": "Sow your gold in the white foliated earth.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "farmer_sowing",
   "golden_seed",
   "white_earth",
   "field",
   "classical_architecture"
  ],
  "imageDesc": "A farmer figure kneels in a plowed field, sowing seed from a bag or pouch into furrows of white or pale earth. The field is carefully tilled in neat rows, and the landscape behind shows a cultivated countryside with distant buildings and trees. The emphasis falls on the act of sowing — the careful p",
  "process": "congelation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-06.jpg"
 },
 "7": {
  "n": 7,
  "roman": "VII",
  "mottoEn": "A young bird flies up from the nest and falls back into the nest again.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "bird_small",
   "nest",
   "tree",
   "sky_vault",
   "falling_arc"
  ],
  "imageDesc": "A young bird — identified in the motto as a philosophical chick — launches upward from a nest perched in a tree or rocky outcrop, wings spread in attempted flight. Below, the same or another bird falls back toward the nest, unable to sustain its ascent. The landscape includes trees and possibly a di",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-07.jpg"
 },
 "8": {
  "n": 8,
  "roman": "VIII",
  "mottoEn": "Take the egg and pierce it with a fiery sword.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "cosmic_egg",
   "fiery_sword",
   "hand_divine",
   "flames",
   "alchemical_vessel"
  ],
  "imageDesc": "A hand extends from the left holding a flaming sword, driving it into a large egg that sits on a surface or pedestal at center. The egg cracks under the blade's impact, and flames or vapors escape from the breach. The setting is minimal, focusing attention entirely on the violent yet precise act of ",
  "process": "digestion",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-08.jpg"
 },
 "9": {
  "n": 9,
  "roman": "IX",
  "mottoEn": "Fix the old man to the tree in the garden of the dew, and the old man becomes young again.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "old_man",
   "tree_garden",
   "dew_drops",
   "youth_figure",
   "garden_walls"
  ],
  "imageDesc": "An old man, stooped with age, is fastened or bound to a tree in what appears to be a garden or orchard. Dew or moisture descends from above — sometimes depicted as rain or celestial drops — onto the old man's body. The garden setting is lush, suggesting the dew is a life-giving rather than punishing",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-09.jpg"
 },
 "10": {
  "n": 10,
  "roman": "X",
  "mottoEn": "Give fire to fire, Mercury to Mercury, and that is enough for you.",
  "mottoLa": "",
  "stage": "CITRINITAS",
  "palette": {
   "primary": "#c8a820",
   "glow": "#ffd000"
  },
  "elements": [
   "fire_flames",
   "mercury_vessel",
   "saturn_devouring",
   "children",
   "alchemical_fire"
  ],
  "imageDesc": "Two fires burn in separate vessels or furnaces, with a figure tending them or directing material between them. Mercury — possibly depicted as a caduceus-bearing figure or as liquid quicksilver — appears in duplicate, being passed from one vessel to another. The composition emphasizes doubling and co",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-10.jpg"
 },
 "11": {
  "n": 11,
  "roman": "XI",
  "mottoEn": "Make Latona white and tear up the books.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "latona_figure",
   "books_torn",
   "whitening_light",
   "classical_scene"
  ],
  "imageDesc": "A female figure identified as Latona stands at center, her skin darkened or stained, while attendants or alchemists work to wash or whiten her body. Books or scrolls lie torn or scattered on the ground around her, their destruction commanded by the motto. The scene combines the act of purification —",
  "process": "congelation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-11.jpg"
 },
 "12": {
  "n": 12,
  "roman": "XII",
  "mottoEn": "Make Latona white and tear up the books.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "latona_figure",
   "whitening_water",
   "classical_scene",
   "sun_rays"
  ],
  "imageDesc": "The composition closely parallels Emblem XI: the figure of Latona appears again in the process of being whitened, while books and scrolls are visibly torn or discarded. The emphasis shifts slightly to the completed act of purification — Latona is lighter or whiter than in the previous emblem, sugges",
  "process": "congelation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-12.jpg"
 },
 "13": {
  "n": 13,
  "roman": "XIII",
  "mottoEn": "The ore of the philosophers is dropsical and wants to be washed seven times in the river, just as Naaman the leper washed in the Jordan.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "naaman_leper",
   "jordan_river",
   "washing_scene",
   "ore_vessel",
   "seven_dips"
  ],
  "imageDesc": "A male figure, possibly identified as Naaman the Syrian, stands immersed in a river — the Jordan — up to his waist or chest. His skin appears spotted or discolored, indicating the leprosy or 'dropsy' of the motto. Attendants or witnesses stand on the riverbank observing the ritual washing. The lands",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-13.jpg"
 },
 "14": {
  "n": 14,
  "roman": "XIV",
  "mottoEn": "This is the dragon that devours its own tail.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "ouroboros_dragon",
   "tail_biting",
   "circular_form",
   "fire_ring"
  ],
  "imageDesc": "A serpent coils upon itself, its jaws clamped around its own tail in the classic ouroboros form. A second serpent approaches or confronts the first, and the scene suggests one devouring the other in a transformative act. The setting is sparse — a rocky or barren ground — focusing attention on the in",
  "process": "putrefaction",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-14.jpg"
 },
 "15": {
  "n": 15,
  "roman": "XV",
  "mottoEn": "Let the work of the potter, consisting of dry and wet, teach you.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "potter",
   "clay_vessel",
   "water",
   "fire_kiln",
   "dry_wet_duality"
  ],
  "imageDesc": "A potter sits at his wheel in a workshop, shaping a vessel from wet clay with his hands. Around him are finished pots in various stages of drying and firing — some still damp, others hardened and glazed. A kiln or furnace glows in the background. The scene emphasizes the craft of working with wet an",
  "process": "congelation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-15.jpg"
 },
 "16": {
  "n": 16,
  "roman": "XVI",
  "mottoEn": "The feathers one lion has not, the other has.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "winged_lion",
   "wingless_lion",
   "comparison_scene",
   "forest"
  ],
  "imageDesc": "Two lions face each other in a confrontational pose. One is winged — feathered pinions spread from its shoulders — while the other is wingless, planted firmly on the ground. The contrast between the aerial, volatile lion and the grounded, fixed lion dominates the composition. The landscape behind th",
  "process": "congelation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-16.jpg"
 },
 "17": {
  "n": 17,
  "roman": "XVII",
  "mottoEn": "A fourfold fire-ball controls this work.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "four_flames",
   "elemental_sphere",
   "four_directions",
   "fire_ball"
  ],
  "imageDesc": "A spherical fireball, divided into four sections or quadrants, hovers or burns at the center of the composition. Each quadrant may represent a different type of fire or heat. Flames radiate outward from the fourfold sphere. A figure — possibly the alchemist — tends or controls the fire from below. T",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-17.jpg"
 },
 "18": {
  "n": 18,
  "roman": "XVIII",
  "mottoEn": "Fire likes making things fiery, but not, like gold, making gold.",
  "mottoLa": "",
  "stage": "CITRINITAS",
  "palette": {
   "primary": "#c8a820",
   "glow": "#ffd000"
  },
  "elements": [
   "fire_figure",
   "gold_ore",
   "transmutation",
   "flames"
  ],
  "imageDesc": "Flames or fire dominate the composition, with a figure working at a furnace or athanor. The fire burns intensely, and various alchemical vessels are arranged around or within the flames. The scene may show the figure adjusting the heat or feeding the fire. The emphasis is on the sustained, controlle",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-18.jpg"
 },
 "19": {
  "n": 19,
  "roman": "XIX",
  "mottoEn": "If you kill one of the four, every body will be dead immediately.",
  "mottoLa": "",
  "stage": "NIGREDO",
  "palette": {
   "primary": "#1a0a00",
   "glow": "#ff4400"
  },
  "elements": [
   "four_elements",
   "earth_water_fire_air",
   "death_of_one",
   "body"
  ],
  "imageDesc": "Four figures stand together in a group — possibly representing four brothers, four elements, or four aspects of a single substance. One figure strikes or kills another while the remaining two look on or collapse. The composition conveys a chain reaction: the death of one precipitates the death of al",
  "process": "separation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-19.jpg"
 },
 "20": {
  "n": 20,
  "roman": "XX",
  "mottoEn": "Nature teaches Nature, Nature conquers Nature, Nature rules Nature.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "hermaphrodite_figure",
   "stone_forming",
   "classical_landscape"
  ],
  "imageDesc": "Three female figures stand in sequence, each teaching or demonstrating something to the next. The first figure may hold a natural object, the second observes or learns, and the third applies what she has learned to overcome or master the preceding figure. The arrangement suggests a pedagogical chain",
  "process": "congelation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-20.jpg"
 },
 "21": {
  "n": 21,
  "roman": "XXI",
  "mottoEn": "Make a circle out of a man and a woman, out of this a square, out of this a triangle, make a circle, and you will have the Philosopher's Stone.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "hermaphrodite_washing",
   "bath_vessel",
   "white_stone",
   "water"
  ],
  "imageDesc": "A geometric diagram at center shows the nested transformation of shapes: a man and woman form a circle, which is inscribed in a square, which contains a triangle, which encloses a final inner circle. The figures may be rendered as human bodies contorted into these geometric forms, or as abstract dia",
  "process": "fixation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-21.jpg"
 },
 "22": {
  "n": 22,
  "roman": "XXII",
  "mottoEn": "When you have obtained the white lead, then do woman's work, that is to say: cook.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "alchemical_bath",
   "purification_scene",
   "woman_man_bathing"
  ],
  "imageDesc": "A woman works at a cooking fire or stove, stirring a pot or vessel containing a white substance — the white lead obtained through the preceding albedo operations. The domestic cooking scene parallels Emblem III's washerwoman: alchemical processes rendered as women's household labor. Kitchen implemen",
  "process": "congelation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-22.jpg"
 },
 "23": {
  "n": 23,
  "roman": "XXIII",
  "mottoEn": "It rains gold when Pallas is born at Rhodes.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "seed_multiplying",
   "field_growth",
   "farmer",
   "hundred_fold"
  ],
  "imageDesc": "Golden rain descends from the sky onto the island or city of Rhodes, where figures reach upward to catch the falling drops. At one side, a helmeted figure — Pallas Athena — emerges fully formed, suggesting her birth from the head of Zeus. The golden precipitation and the goddess's birth occur simult",
  "process": "projection",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-23.jpg"
 },
 "24": {
  "n": 24,
  "roman": "XXIV",
  "mottoEn": "The wolf devoured the king, and after the wolf had been burnt, it returned the king to life.",
  "mottoLa": "",
  "stage": "CITRINITAS",
  "palette": {
   "primary": "#c8a820",
   "glow": "#ffd000"
  },
  "elements": [
   "sun_moon_conjunction",
   "celestial_scene",
   "transition"
  ],
  "imageDesc": "A wolf stands over the prostrate body of a crowned king, having devoured or killed him. In a second register or scene within the same plate, the wolf is shown consumed by flames on a pyre, and the king rises restored from the ashes or emerges renewed from the fire. The sequential narrative moves fro",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-24.jpg"
 },
 "25": {
  "n": 25,
  "roman": "XXV",
  "mottoEn": "The Dragon does not die, if it is not killed by its brother and sister, that is to say by Sol and Luna.",
  "mottoLa": "",
  "stage": "ALBEDO",
  "palette": {
   "primary": "#e8e4dc",
   "glow": "#ffffff"
  },
  "elements": [
   "whitening_final",
   "stone_white",
   "classical_setting"
  ],
  "imageDesc": "A dragon writhes at center, locked in combat with two figures — a male and female identified as Sol and Luna, or brother and sister. The dragon is wounded or dying but still dangerous. The male figure wields a weapon while the female restrains or applies a substance to the dragon's body. The scene t",
  "process": "putrefaction",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-25.jpg"
 },
 "26": {
  "n": 26,
  "roman": "XXVI",
  "mottoEn": "The fruit of human wisdom is the Tree of Life.",
  "mottoLa": "",
  "stage": "CITRINITAS",
  "palette": {
   "primary": "#c8a820",
   "glow": "#ffd000"
  },
  "elements": [
   "yellowing_scene",
   "citrinitas_light",
   "transition_space"
  ],
  "imageDesc": "A female figure identified as Lady Sapientia (Wisdom) stands beside or beneath a large tree bearing golden fruit — the Tree of Life. She may hold a book, a scepter, or extend a hand toward the fruit. The tree is abundant and flourishing, its canopy spreading over the scene. The setting is a garden o",
  "process": "fermentation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-26.jpg"
 },
 "27": {
  "n": 27,
  "roman": "XXVII",
  "mottoEn": "He who tries to enter the Philosophical Rose-garden without the key is like a man who wants to walk without feet.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "king_figure",
   "queen_figure",
   "wedding_chamber",
   "bed",
   "alchemical_union"
  ],
  "imageDesc": "A figure approaches or stands before a walled garden containing rose bushes or flowering plants. A locked gate or door bars entry, and the figure has no key. The garden interior is visible — lush, ordered, containing the philosophical rose — but inaccessible. The composition emphasizes the barrier b",
  "process": "fermentation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-27.jpg"
 },
 "28": {
  "n": 28,
  "roman": "XXVIII",
  "mottoEn": "The king is bathed, sitting in a steam-bath, and is freed from the black bile by Pharut.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "king_crowned",
   "queen_crowned",
   "throne",
   "celestial_orbs",
   "sceptre"
  ],
  "imageDesc": "A crowned king sits immersed in a steaming bath or vessel, attended by one or more figures — physicians or servants — who regulate the temperature or administer treatments. Black bile or dark fluid visibly drains from the king's body into the bathwater. The bath vessel is large and prominent, and st",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-28.jpg"
 },
 "29": {
  "n": 29,
  "roman": "XXIX",
  "mottoEn": "Just as the Salamander lives in the fire, so also the Stone.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "hermaphrodite_crowned",
   "rising_figure",
   "victory",
   "celestial_light"
  ],
  "imageDesc": "A salamander sits calmly within flames, unharmed by the fire that surrounds it. The fire burns vigorously — depicted with detailed, curling flames — but the creature rests at ease in the center. The scene may include a furnace or hearth as the fire's source. The salamander's composure within the des",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-29.jpg"
 },
 "30": {
  "n": 30,
  "roman": "XXX",
  "mottoEn": "The Hermaphrodite, lying in darkness like a dead man, needs fire.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "sun_disc",
   "moon_crescent",
   "unity_scene",
   "light_rays"
  ],
  "imageDesc": "A figure with both male and female characteristics — the Hermaphrodite or Rebis — lies in darkness, motionless as if dead, upon a bed or bier. The surrounding space is black or deeply shadowed. A fire or torch approaches from one side, about to illuminate and revive the prostrate figure. The Hermaph",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-30.jpg"
 },
 "31": {
  "n": 31,
  "roman": "XXXI",
  "mottoEn": "The king, swimming in the sea, calling in a loud voice: He who saves me will receive a great reward.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "king_enthroned",
   "solar_crown",
   "red_robes",
   "court"
  ],
  "imageDesc": "A crowned king struggles in ocean waves, his head and arms above the surface, calling out for rescue. His crown identifies him as royalty even in distress. From the shore or from a boat, a figure reaches toward the king or prepares to pull him from the water. The sea is rough, with whitecaps, and th",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-31.jpg"
 },
 "32": {
  "n": 32,
  "roman": "XXXII",
  "mottoEn": "As coral grows under water and, exposed to the air, gets hard, so also the Stone.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "red_stone",
   "multiplication",
   "transmutation_vessels",
   "projection"
  ],
  "imageDesc": "A branch of coral grows underwater, depicted in its natural marine setting with fish and sea creatures nearby. In a second register, the same coral is shown above the waterline, where it has hardened into a rigid, stone-like form. The contrast between the soft, underwater growth and the hard, aerial",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-32.jpg"
 },
 "33": {
  "n": 33,
  "roman": "XXXIII",
  "mottoEn": "The Hermaphrodite, lying in darkness like a dead man, needs fire.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "hermaphrodite_full",
   "androgyne",
   "crown",
   "dual_nature",
   "light"
  ],
  "imageDesc": "The Hermaphrodite figure lies in complete darkness on a bier or bed, as in Emblem XXX, but now more explicitly dead or death-like. The surrounding blackness is total — the nigredo at its deepest. Fire or a flame-bearing figure approaches, representing the intervention of heat that will begin the pro",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-33.jpg"
 },
 "34": {
  "n": 34,
  "roman": "XXXIV",
  "mottoEn": "He is conceived in the bath and born in the air, but having become red he walks upon the waters.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "hermaphrodite_detail",
   "masculine_feminine_merged",
   "symbolism"
  ],
  "imageDesc": "A celestial scene depicts a conception or hierogamy — a sacred marriage between heavenly figures. Rays of light or celestial fire descend from above onto a figure below who receives or conceives from the divine influence. Stars, planets, or zodiacal imagery may appear in the sky. The composition ele",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-34.jpg"
 },
 "35": {
  "n": 35,
  "roman": "XXXV",
  "mottoEn": "As Ceres accustomed Triptolemus, and Thetis Achilles, to endure fire, so the artist does with the Stone.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "dead_king",
   "resurrection",
   "tomb",
   "light_emerging",
   "angel"
  ],
  "imageDesc": "A figure identified as Ceres or Thetis holds a child — Triptolemus or Achilles — over flames, tempering the child in fire to make it immortal or invulnerable. The fire burns beneath or around the child's body while the mother-figure supports it with care. A second figure may look on with alarm at th",
  "process": "calcination",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-35.jpg"
 },
 "36": {
  "n": 36,
  "roman": "XXXVI",
  "mottoEn": "The Stone has been thrown on to the earth and lifted on to the mountains, and it dwells in the air and feeds in the river.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "pelican_feeding",
   "chicks",
   "blood",
   "nest",
   "sacrifice"
  ],
  "imageDesc": "A large stone lies on the ground where it has been thrown or deposited, while in a second register the same stone is shown elevated on a mountaintop. The landscape shifts between low valley and high peak. A figure may be shown casting the stone downward or carrying it upward. The dual positioning ca",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-36.jpg"
 },
 "37": {
  "n": 37,
  "roman": "XXXVII",
  "mottoEn": "Three things are sufficient for mastery: white smoke, that is water, the green Lion, that is the Ore of Hermes, and stinking water.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "phoenix_rising",
   "flames",
   "ash",
   "rebirth",
   "sun_above"
  ],
  "imageDesc": "Three distinct substances or elements are displayed or arranged together: a plume of white smoke rising from a vessel, a green lion (a vitreous or green-tinged substance), and dark, foul-smelling water. The three may be shown in separate vessels or combined in a single scene. A figure surveys or pre",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-37.jpg"
 },
 "38": {
  "n": 38,
  "roman": "XXXVIII",
  "mottoEn": "The Hermaphrodite, born of two mountains, of Mercury and Venus.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "hermaphrodite_crowned_victory",
   "classical_landscape",
   "triumph"
  ],
  "imageDesc": "The Hermaphrodite stands upright and fully formed, displaying both male and female attributes in a single body. Unlike the prostrate Hermaphrodite of Emblems XXX and XXXIII, this figure is erect, active, and complete — the product of the union of opposites now realized. The figure stands on or betwe",
  "process": "conjunction",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-38.jpg"
 },
 "39": {
  "n": 39,
  "roman": "XXXIX",
  "mottoEn": "Oedipus, having conquered the Sphinx and having killed his father Laius, married his mother Jocasta.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "stone_manifest",
   "radiance",
   "alchemical_apparatus",
   "projection"
  ],
  "imageDesc": "Oedipus confronts the Sphinx on a rocky outcrop or mountainside. The Sphinx — part woman, part lion, part eagle — poses its riddle while Oedipus responds. In the background or a secondary scene, the consequences of the story unfold: Oedipus's father Laius lies dead, and the marriage to Jocasta is su",
  "process": "separation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-39.jpg"
 },
 "40": {
  "n": 40,
  "roman": "XL",
  "mottoEn": "Make one water out of two waters, and it will be the water of holiness.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "stone_multiplying",
   "vessels",
   "transmutation",
   "gold_forming"
  ],
  "imageDesc": "Two streams or bodies of water flow toward each other and merge into a single river or pool. The two waters may be distinguished by color — one clear, one dark, or one golden, one silver. A figure may direct or channel the confluence. The merging point is the focal center of the composition, where t",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-40.jpg"
 },
 "41": {
  "n": 41,
  "roman": "XLI",
  "mottoEn": "Adonis is killed by a boar, and Venus, rushing up to him, painted the roses red with her blood.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "stone_conquering",
   "metals_converting",
   "king_stone",
   "victory"
  ],
  "imageDesc": "Adonis lies wounded or dead in a woodland setting, gored by a wild boar that stands nearby or flees the scene. Venus rushes toward Adonis, her robes flowing with urgency. Blood flows from Adonis's wounds onto white roses growing nearby, staining them red. The transformation of the roses from white t",
  "process": "separation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-41.jpg"
 },
 "42": {
  "n": 42,
  "roman": "XLII",
  "mottoEn": "What Nature, Reason, Experience and Reading teach you, let that be the fire, the vessel, the water and the earth.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "king_and_stone",
   "throne_room",
   "royal_court",
   "alchemical_emblem"
  ],
  "imageDesc": "Four figures or personifications are arranged in the composition, each representing one of the guides to the alchemical work: Nature (a female figure), Reason (perhaps holding a book or compass), Experience (a laboratory figure), and Reading (a scholar with books). They may surround or point toward ",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-42.jpg"
 },
 "43": {
  "n": 43,
  "roman": "XLIII",
  "mottoEn": "Listen to the screech owl's voice, which it produces it self, and the water and do not heed any bird that cries in the evening.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "stone_as_medicine",
   "healing_scene",
   "figures_restored",
   "light"
  ],
  "imageDesc": "A screech owl or night bird perches prominently, its beak open as if calling. Nearby, water flows — a stream, fountain, or rain — and the scene is set at dusk or in dim light. Other birds may be visible in the evening sky, their calls contrasting with the owl's solitary voice. The composition emphas",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-43.jpg"
 },
 "44": {
  "n": 44,
  "roman": "XLIV",
  "mottoEn": "Typhon kills Osiris by a ruse, and after that he scatters his limbs far and wide, but Is is gathers them together again.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "sol_figure",
   "luna_figure",
   "final_conjunction",
   "celestial_embrace"
  ],
  "imageDesc": "Typhon, depicted as a monstrous figure, strikes down or dismembers Osiris, whose body lies scattered in fragments across the landscape. In a secondary scene, the goddess Isis moves through the landscape gathering the scattered limbs, reassembling the divine body. The composition narrates dissolution",
  "process": "separation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-44.jpg"
 },
 "45": {
  "n": 45,
  "roman": "XLV",
  "mottoEn": "Sol and his shadow complete the work.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "sublimation_vessel",
   "spirit_ascending",
   "completion"
  ],
  "imageDesc": "Sol and Luna — depicted as a king and queen, or as the sun and moon personified — stand together with their shadows visible or prominent. The shadows may merge or interact in ways the figures themselves do not, suggesting that the hidden, shadow aspect of the work is where the real operation occurs.",
  "process": "multiplication",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-45.jpg"
 },
 "46": {
  "n": 46,
  "roman": "XLVI",
  "mottoEn": "Two eagles meet, the one from the East, the other from the West.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "quintessence_distilling",
   "five_elements",
   "celestial_apparatus"
  ],
  "imageDesc": "Two eagles fly toward each other from opposite directions — one from the East (the right), the other from the West (the left). They meet in mid-air, their talons or beaks engaging at the point of collision. The landscape below stretches between two horizons, emphasizing the vast distance the eagles ",
  "process": "multiplication",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-46.jpg"
 },
 "47": {
  "n": 47,
  "roman": "XLVII",
  "mottoEn": "The wolf coming from the East, and the Dog coming from the West, have bitten each other.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "stone_projection",
   "base_metal",
   "gold_transformation",
   "flame"
  ],
  "imageDesc": "A wolf approaches from one side and a dog from the other, meeting in a violent confrontation. They bite and tear at each other, locked in mutual combat. The wolf is identified with the East and the dog with the West. The landscape suggests a meeting point between two territories, with the struggle o",
  "process": "separation",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-47.jpg"
 },
 "48": {
  "n": 48,
  "roman": "XLVIII",
  "mottoEn": "The king, fallen ill from drinking, is restored to health by a physician.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "king_steam_bath",
   "sweat_house",
   "attendants",
   "heat",
   "renewal"
  ],
  "imageDesc": "A king reclines on a bed or throne, visibly ill — his complexion pale or discolored, his posture weakened. Physicians or attendants approach with a vessel containing a potion or elixir, preparing to administer the remedy. The setting suggests a royal sickroom or court. The king wears his crown even ",
  "process": "fusion",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-48.jpg"
 },
 "49": {
  "n": 49,
  "roman": "XLIX",
  "mottoEn": "The Philosophical Child acknowledges three fathers, just as Orion.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "dying_king",
   "dissolution",
   "grief_figures",
   "transformation"
  ],
  "imageDesc": "A child — the Philosophical Child — stands or sits at center, flanked by three male figures identified as his three fathers. The child may display characteristics of all three, or the three fathers may each contribute a different gift or quality. The myth of Orion's triple parentage provides the nar",
  "process": "multiplication",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-49.jpg"
 },
 "50": {
  "n": 50,
  "roman": "L",
  "mottoEn": "The Dragon kills the woman, and she kills it, and together they bathe in blood.",
  "mottoLa": "",
  "stage": "RUBEDO",
  "palette": {
   "primary": "#8b0000",
   "glow": "#ffcc00"
  },
  "elements": [
   "philosophers_stone",
   "crowned_completion",
   "sol_luna_unified",
   "radiance",
   "ouroboros"
  ],
  "imageDesc": "A dragon and a woman are locked in mortal combat, each killing the other simultaneously. The dragon's coils wrap around the woman's body while she strikes at its head or throat. Blood flows from both combatants. The scene takes place in a cave-like or underground setting, near a body of water or poo",
  "process": "solution",
  "img": "/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-50.jpg"
 }
};
