// ===========================================================================
// processes.js — the alchemical process (operation) library used for the
// "lab process tours." Physical/chemical readings after Principe, Newman,
// Moran, and Rampling (The Experimental Fire) for Ripley's Twelve Gates.
// Each plate in the catalog links to one of these via processmap.js.
// ===========================================================================

export const PROCESSES = {
  calcination: { key:"calcination", name:"Calcination", gate:"Calcination",
    summary:"Heating a solid in air until it is reduced to a dry, friable powder (a calx), driving off volatile matter and oxidising a metal to its ash.",
    steps:["Grind the material and load it into an open crucible","Set the crucible in the furnace over open coals","Drive the fire with bellows; hold a strong heat for hours","Rake the powder to expose fresh surfaces","Cool and collect the resulting calx"],
    apparatus:["crucible","furnace","bellows","tongs","mortar"], lab:"base", heat:"open coals", color:"nigredo",
    cite:"Principe, The Secrets of Alchemy (2013)" },
  solution: { key:"solution", name:"Solution (Dissolution)", gate:"Solution",
    summary:"Reducing a solid to a liquid by dissolving it in a corrosive water (acid) or menstruum, 'opening' the body for further work.",
    steps:["Prepare the menstruum in a glass vessel","Add the powdered body in small portions","Set on a gentle water-bath to aid dissolution","Wait until effervescence ceases","Filter off any undissolved residue"],
    apparatus:["glass flask","balneum","filter"], lab:"base", heat:"water-bath", color:null,
    cite:"Newman, Chymistry of Isaac Newton" },
  separation: { key:"separation", name:"Separation", gate:"Separation",
    summary:"Parting the pure from the impure by filtration, decantation, or splitting volatile from fixed fractions.",
    steps:["Let the mixture settle so heavy matter sinks","Decant or filter the clear liquor from the dregs","Apply gentle heat to part volatile from fixed","Collect each fraction separately","Set aside the purified portion"],
    apparatus:["filter","funnel","separating vessel","balneum"], lab:"base", heat:"gentle/dung-heat", color:null,
    cite:"Principe, The Secrets of Alchemy (2013)" },
  conjunction: { key:"conjunction", name:"Conjunction", gate:"Conjunction",
    summary:"Recombining the separated, purified parts (the 'marriage' of fixed body and volatile spirit) into one unified compound.",
    steps:["Weigh the purified body and spirit","Combine them in a clean glass vessel","Triturate to a homogeneous mixture","Seal against loss of spirit","Set in gentle warmth to let the parts unite"],
    apparatus:["glass flask","sealed vessel","mortar","balneum"], lab:"base", heat:"gentle/dung-heat", color:null,
    cite:"Rampling, The Experimental Fire (2020)" },
  putrefaction: { key:"putrefaction", name:"Putrefaction", gate:"Putrefaction",
    summary:"Holding sealed matter at low steady heat until it darkens and rots — the 'blackening' that is the body's death before regeneration.",
    steps:["Seal the conjoined matter in a glass egg","Bed the vessel in warm dung or the athanor's mild heat","Maintain a constant gentle warmth, uninterrupted","Watch the matter blacken over days or weeks","Hold until the blackness is complete"],
    apparatus:["philosophical egg","athanor","dung-bed"], lab:"base", heat:"gentle/dung-heat", color:"nigredo",
    cite:"Principe, The Secrets of Alchemy (2013)" },
  congelation: { key:"congelation", name:"Congelation (Coagulation)", gate:"Congelation",
    summary:"Turning a liquid or dissolved matter back into a solid by slow evaporation, fixing it into a coagulated, often white, body.",
    steps:["Place the solution in a shallow dish","Apply gentle ash- or sand-bath heat to evaporate","Concentrate until a film or crystals form","Let it stand to set into a solid","Scrape and collect the coagulated body"],
    apparatus:["evaporating dish","sand-bath","glass flask"], lab:"base", heat:"ash/sand-bath", color:"albedo",
    cite:"Newman, Chymistry of Isaac Newton" },
  cibation: { key:"cibation", name:"Cibation", gate:"Cibation",
    summary:"Feeding the maturing matter measured portions of fresh liquid — 'nourishing' it at intervals like an infant so it can grow and digest.",
    steps:["Prepare the feeding liquor","Imbibe a small measured dose into the matter","Reseal and return to gentle heat","Let it dry and absorb before the next dose","Repeat the imbibition in graded amounts"],
    apparatus:["philosophical egg","athanor","dropper","balneum"], lab:"base", heat:"gentle/dung-heat", color:"albedo",
    cite:"Rampling, The Experimental Fire (2020)" },
  sublimation: { key:"sublimation", name:"Sublimation", gate:"Sublimation",
    summary:"Heating a solid so it vaporises and re-condenses directly as a purer solid on the cool upper vessel, leaving dross behind.",
    steps:["Charge the aludel with the powdered matter","Set it over sand- or ash-bath heat","Raise the heat so vapours rise without melting","Let the sublimate condense above","Scrape down the flowers; discard the caput mortuum"],
    apparatus:["aludel","sand-bath","furnace","scraper"], lab:"Sublimation Vault", heat:"ash/sand-bath", color:"albedo",
    cite:"Martelli, Greek Alchemists at Work (Nuncius 2011)" },
  distillation: { key:"distillation", name:"Distillation", gate:null,
    summary:"Vaporising a liquid and condensing it in a cooled receiver to separate volatile spirits from a fixed residue, purifying by repeated runs.",
    steps:["Charge the cucurbit and fit the alembic head","Lute the joints airtight; attach the receiver","Apply graded water- or sand-bath heat","Cool the still-head so distillate runs to the receiver","Collect fractions in order; cohobate if needed"],
    apparatus:["alembic","cucurbit","retort","receiver","luting clay"], lab:"Distillation Hall", heat:"water-bath", color:null,
    cite:"Principe, The Secrets of Alchemy (2013)" },
  digestion: { key:"digestion", name:"Digestion", gate:null,
    summary:"Holding matter at low, constant warmth in a sealed vessel for a prolonged period so its parts slowly react, mature, and 'concoct.'",
    steps:["Seal the matter in a stoppered glass vessel","Set it in a balneum or the athanor's gentle warmth","Hold a low, unvarying heat for days to months","Observe gradual colour and texture changes","Continue until the matter is fully concocted"],
    apparatus:["athanor","balneum","sealed vessel","pelican"], lab:"base", heat:"gentle/dung-heat", color:null,
    cite:"Newman, Chymistry of Isaac Newton" },
  fermentation: { key:"fermentation", name:"Fermentation", gate:"Fermentation",
    summary:"Adding a 'ferment' (often gold) to the prepared stone so it takes on its nature and tinging power, as leaven works dough.",
    steps:["Purify the chosen ferment (e.g. gold)","Melt or soften ferment and stone together","Incorporate them in measured proportion","Seal and set on gentle heat","Hold until the mass is uniformly imbued"],
    apparatus:["crucible","athanor","sealed vessel","mortar"], lab:"base", heat:"ash/sand-bath", color:"citrinitas",
    cite:"Rampling, The Experimental Fire (2020)" },
  fixation: { key:"fixation", name:"Fixation", gate:null,
    summary:"Rendering a volatile substance stable so it withstands fire without subliming — 'fixing' the spirit permanently into the body.",
    steps:["Combine the volatile spirit with its fixed body","Seal in a fire-resistant vessel","Apply progressively stronger heat in stages","Test a sample in the flame to see it no longer flies","Raise the fire until wholly fixed"],
    apparatus:["crucible","athanor","furnace","sealed vessel"], lab:"Assay Furnace", heat:"open coals", color:null,
    cite:"Principe, The Secrets of Alchemy (2013)" },
  fusion: { key:"fusion", name:"Fusion (Regulus)", gate:null,
    summary:"Melting an ore with a flux so the heavy purified metal (the regulus) sinks and collects as a button beneath the slag.",
    steps:["Mix the crushed ore with flux and reducer","Load the charge into a strong crucible","Drive the furnace to a fierce melting heat","Hold molten until the regulus settles below the slag","Cool, then break out the metallic button"],
    apparatus:["crucible","blast furnace","bellows","ingot mold","flux"], lab:"Assay Furnace", heat:"fierce/fusion", color:null,
    cite:"Newman, Chymistry of Isaac Newton" },
  exaltation: { key:"exaltation", name:"Exaltation", gate:"Exaltation",
    summary:"Raising the matter to its highest, most refined and potent condition through repeated purifying cycles.",
    steps:["Take the matured, fixed matter","Cycle it through dissolving and coagulating","Discard the dregs thrown off each round","Raise the heat in stages","Continue until it reaches its purest state"],
    apparatus:["pelican","athanor","glass flask","sand-bath"], lab:"base", heat:"ash/sand-bath", color:"rubedo",
    cite:"Rampling, The Experimental Fire (2020)" },
  multiplication: { key:"multiplication", name:"Multiplication", gate:"Multiplication",
    summary:"Increasing the quantity and tinging power of the finished stone by feeding it fresh mercury and re-digesting; each cycle augments its strength.",
    steps:["Dissolve a portion of the stone in fresh mercury","Seal the mixture in a clean vessel","Digest at gentle heat to incorporate the new matter","Coagulate back to a solid","Repeat to multiply quantity and potency"],
    apparatus:["philosophical egg","athanor","balneum","sealed vessel"], lab:"base", heat:"gentle/dung-heat", color:"rubedo",
    cite:"Rampling, The Experimental Fire (2020)" },
  projection: { key:"projection", name:"Projection", gate:"Projection",
    summary:"The final operation: casting a grain of the finished stone onto molten base metal to transmute it — the climactic bench test.",
    steps:["Melt the base metal in a crucible to a clean flux","Wrap a measured grain of the stone","Cast the powder of projection onto the melt","Stir and hold briefly to let it work through","Pour out and assay the resulting metal"],
    apparatus:["crucible","furnace","bellows","ingot mold"], lab:"Assay Furnace", heat:"fierce/fusion", color:"rubedo",
    cite:"Principe, The Secrets of Alchemy (2013)" },
};

export const SPECIALIZED_LABS = {
  "Distillation Hall": { name:"Distillation Hall",
    purpose:"Running stills to separate and purify volatile spirits and waters.",
    apparatus:["alembic","cucurbit","retort","condenser","receiver"],
    why:"Needs fragile fitted glass trains, cooling, and luting a plain bench cannot host." },
  "Assay Furnace": { name:"Assay Furnace",
    purpose:"High-heat melting, fusion, fixation, and metal testing/transmutation.",
    apparatus:["blast furnace","bellows","cupel","ingot mold","flux"],
    why:"Requires forced-draft fierce heat and metallurgical fixtures beyond an athanor." },
  "Sublimation Vault": { name:"Sublimation Vault",
    purpose:"Subliming solids into purified 'flowers.'",
    apparatus:["aludel","tiered pots","sand-bath"],
    why:"Needs tall tiered sublimatories, a managed gradient, and ventilation for toxic vapours." },
  "Glasshouse": { name:"Glasshouse",
    purpose:"Blowing and fitting the eggs, pelicans and retorts the other labs consume.",
    apparatus:["glass furnace","blowpipe","annealing oven"],
    why:"Demands a dedicated continuous glass furnace and annealing." },
};
