#!/usr/bin/env python3
"""Generate emblemdata.js (rich per-emblem data for the scene engine) and
processmap.js (every plate -> alchemical process key) from the claudiens DB
dump (emblem_raw.json) + the HP woodcut folder. Heuristic process assignment
keyed to alchemical stage + motto keywords (a thematic pairing, not a claim
that each emblem 'is' that operation)."""
import os, re, json

HERE = r"C:/Dev/EMBLEMSIN3D"
RAW = os.path.join(HERE, "tools", "emblem_raw.json")
HP_DIR = r"C:/Dev/EmblemPrintShop/sources/hypnerotomachia-polyphili/site/images/woodcuts_1499"

PROC_KEYS = ["calcination","solution","separation","conjunction","putrefaction",
             "congelation","cibation","sublimation","distillation","digestion",
             "fermentation","fixation","fusion","exaltation","multiplication","projection"]

STAGE_DEFAULT = {"NIGREDO":"calcination","ALBEDO":"congelation",
                 "CITRINITAS":"fermentation","RUBEDO":"multiplication","":"digestion"}

# motto keyword -> process (first match wins)
KW = [
    (r"egg|gladio|sword", "digestion"),
    (r"distil|alembic", "distillation"),
    (r"bath|steam|swim|sea|wash|river|water|dew", "solution"),
    (r"burn|fire|fiery|salamander|flame", "calcination"),
    (r"dragon|devour|tail|putref|rot|black", "putrefaction"),
    (r"wolf|dog|bite|kill|sphinx|boar", "separation"),
    (r"join|marry|wedd|brother and sister|hermaphrodite|conjunc|cup of love", "conjunction"),
    (r"white|latona|wash.*seven|foliated", "congelation"),
    (r"sow|seed|earth|grow|tree|garden", "fermentation"),
    (r"gold|rains gold|pallas|projection|tincture", "projection"),
    (r"multipl|increase", "multiplication"),
    (r"sublim|smoke|spirit rises", "sublimation"),
    (r"fix|stone|coral|hard", "fixation"),
    (r"wolf.*king|regulus|antimony|mars|vulcan|ore", "fusion"),
]

def pick_process(motto, stage):
    m = (motto or "").lower()
    for pat, key in KW:
        if re.search(pat, m):
            return key
    return STAGE_DEFAULT.get((stage or "").upper().strip(), "digestion")

def parse_palette(s):
    if not s:
        return {"primary": "#2a2018", "glow": "#caa45a"}
    try:
        d = json.loads(s)
        if isinstance(d, dict):
            prim = d.get("primary") or d.get("base") or d.get("bg") or "#2a2018"
            glow = d.get("glow") or d.get("accent") or d.get("highlight") or "#caa45a"
            return {"primary": prim, "glow": glow}
    except Exception:
        pass
    # fall back: grab first two hex colors
    hexes = re.findall(r"#[0-9a-fA-F]{6}", s)
    return {"primary": hexes[0] if hexes else "#2a2018",
            "glow": hexes[1] if len(hexes) > 1 else "#caa45a"}

def parse_elements(s):
    if not s:
        return []
    try:
        v = json.loads(s)
        if isinstance(v, list):
            return [str(x).strip().lower() for x in v if str(x).strip()]
    except Exception:
        pass
    return [t.strip().lower() for t in re.split(r"[;,]", s) if t.strip()]

raw = json.load(open(RAW, encoding="utf-8"))
emblemdata = {}
af_proc = {}
for d in raw:
    n = d["number"]
    motto = d.get("motto_english") or ""
    stage = (d.get("alchemical_stage") or "").upper().strip()
    proc = pick_process(motto, stage)
    af_proc[n] = proc
    emblemdata[n] = {
        "n": n,
        "roman": d.get("roman_numeral") or "",
        "mottoEn": motto.replace("\n", " ").strip(),
        "mottoLa": (d.get("motto_latin") or "").replace("\n", " ").strip(),
        "stage": stage,
        "palette": parse_palette(d.get("stage_palette")),
        "elements": parse_elements(d.get("visual_elements")),
        "imageDesc": (d.get("image_description") or "").replace("\n", " ").strip()[:300],
        "process": proc,
        "img": f"/EmblemPrintShop/sources/claudiens/site/images/emblems/emblem-{n:02d}.jpg",
    }

# process map for all plates
pmap = {}
for n, p in af_proc.items():
    pmap[f"af-{n:02d}"] = p
# HP woodcuts: cycle through the process list so each plate links to a tour
hp_files = sorted(f for f in os.listdir(HP_DIR) if re.match(r"hp1499_p\d+\.jpg$", f))
for i, f in enumerate(hp_files):
    fol = re.search(r"_p(\d+)", f).group(1)
    pmap[f"hp-{fol}"] = PROC_KEYS[i % len(PROC_KEYS)]

with open(os.path.join(HERE, "emblemdata.js"), "w", encoding="utf-8") as fh:
    fh.write("// AUTO-GENERATED by tools/gen_emblemdata.py — do not edit by hand.\n")
    fh.write("export const EMBLEMDATA = " + json.dumps(emblemdata, ensure_ascii=False, indent=1) + ";\n")

# NOTE: processmap.js is now written by tools/gen_catalog.py (it knows every
# collection — emblems, woodcuts, and the occult archive). Left here for ref.

# report
from collections import Counter
print("emblems:", len(emblemdata), "| plates mapped:", len(pmap))
print("AF process distribution:", Counter(af_proc.values()))
