#!/usr/bin/env python3
"""Generate emblem_explanations.js from the Claudiens DB: a short main-idea
summary (discourse_summary) and a deep-dive (analysis_html) per emblem, for the
accordion on the per-emblem fugue page."""
import sqlite3, json, os

DB = r"C:/Dev/Claudiens/db/atalanta.db"
OUT = r"C:/Dev/EMBLEMSIN3D/emblem_explanations.js"

con = sqlite3.connect(DB); con.row_factory = sqlite3.Row
data = {}
for r in con.execute("SELECT number, roman_numeral, motto_english, epigram_english, discourse_summary, analysis_html, image_description FROM emblems ORDER BY number"):
    n = r["number"]
    short = (r["discourse_summary"] or "").strip()
    deep = (r["analysis_html"] or "").strip()
    if not deep:
        # frontispiece / missing analysis: build a deep view from what we have
        bits = []
        if r["image_description"]: bits.append("<p>" + r["image_description"].strip() + "</p>")
        if r["discourse_summary"]: bits.append("<p>" + r["discourse_summary"].strip() + "</p>")
        deep = "\n".join(bits) or "<p>(No extended analysis on record for this plate.)</p>"
    data[n] = {
        "roman": r["roman_numeral"] or "",
        "motto": (r["motto_english"] or "").replace("\n", " ").strip(),
        "epigram": (r["epigram_english"] or "").strip(),
        "short": short,
        "deep": deep,
    }
con.close()

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("// AUTO-GENERATED by tools/gen_explanations.py from the Claudiens DB.\n")
    fh.write("// Per-emblem explanations: short main idea + deep-dive analysis (HTML).\n")
    fh.write("export const EXPLAIN = " + json.dumps(data, ensure_ascii=False) + ";\n")

print("wrote", OUT, "emblems:", len(data),
      "| with deep analysis:", sum(1 for v in data.values() if v["deep"]))
